name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install dependencies
        run: cd src && go mod download

      - name: Build
        run: cd src && go build -v -o ../bin/diorama

      - name: Run vet & lint
        run: |
          cd src
          go vet .
          golint .
